### ISSUE TITLE
Add all njs declarations to index.d.ts

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs-typescript#1]

**Comment by DSanborn** [comment]
Thanks for adding the declarations, but I could use some help hooking these up with webpack/ts-loader. When trying to debug (outside of the neutralino-linux executable) I get the following run-time error:
```
/home/user12345/.nvm/versions/node/v13.11.0/bin/node --harmony --inspect-brk=28256 app/assets/app.js 
Debugger listening on ws://127.0.0.1:28256/1023865f-b2c2-4fdc-8a9d-303dd2bb7245
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
ReferenceError: Neutralino is not defined
    at Module.<anonymous> (/home/dsanborn/git/wilbur2/src/app.ts:49:1)
    at n (/home/dsanborn/git/wilbur2/app/assets/app.js:1:110)
    at /home/dsanborn/git/wilbur2/app/assets/app.js:1:902
    at Object.<anonymous> (/home/dsanborn/git/wilbur2/node_modules/inversify/lib/constants/metadata_keys.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1144:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
